name: "GoChopChop"
description: "ChopChop is a tool for dynamic application security testing on web applications"
branding:
  icon: "target"
  color: "gray-dark"
inputs:
  host:
    description: 'The host to scan. Example : "https://example.net"'
    required: true
  maxSeverity:
    description: 'The maximum severity to be allowed. Examples : "Low" / "Medium" / "High"'
    required: false
    default: "Low"
  httpRequestTimeout:
    description: 'The maximum time to wait for a HTTP response. Example : "10"'
    required: false
    default: "10"
  signatures:
    description: 'The path to the signatures file. Example : ".chopchop/rules.yml"'
    required: false
    default: "/tmp/chopchop.yml"
  userAgent:
    description: 'The user agent to use for HTTP requests. Example : "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"'
    required: false
    default: "ChopChop"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "scan"
    - ${{ inputs.host }}
    - "--signatures"
    - ${{ inputs.signatures }}
    - "--max-severity"
    - ${{ inputs.maxSeverity }}
    - "--timeout"
    - ${{ inputs.httpRequestTimeout }}
    - "--user-agent"
    - ${{ inputs.userAgent }}
