name: ChopChop Action
on:
  workflow_dispatch:
    inputs:
      host:
        description: "Host to scan"
        required: true
        default: "https://example.net"
      maxSeverity:
        description: "Maximum severity to be allowed"
        required: false
        default: "Low"
        type: choice
        options: 
        - Low
        - Medium
        - High
      httpRequestTimeout:
        description: "Maximum time to wait for a HTTP response"
        required: false
        default: "10"
      userAgent:
        description: "User agent to use for HTTP requests"
        required: false
        default: "ChopChop"

jobs:
  chopchop-action-job:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    name: A job to test the ChopChop action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Default ChopChop Scan
        uses: ./
        with:
          host: ${{ github.event.inputs.host }}
      - name: Custom ChopChop Scan
        uses: ./
        with:
          host: ${{ github.event.inputs.host }}
          signatures: ".chopchop/test_rules.yml"
